apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-route
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /webapp1
            pathType: Prefix
            backend:
              service:
                name: webapp1-svc
                port:
                  number: 8080